slowphp.lo: /home/renlu/devel/php_ext/slowphp/slowphp.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/renlu/devel/php_ext/slowphp $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/renlu/devel/php_ext/slowphp/slowphp.c -o slowphp.lo 
$(phplibdir)/slowphp.la: ./slowphp.la
	$(LIBTOOL) --mode=install cp ./slowphp.la $(phplibdir)

./slowphp.la: $(shared_objects_slowphp) $(SLOWPHP_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_slowphp) $(SLOWPHP_SHARED_LIBADD)

